### ISSUE TITLE
Issues to be fixed before submitting the extension

### ISSUE THREAD

**Issue by lassoan** [ReynoldsJ20/SlicerFiducialsToModelDistance#3]
- [x] Typo: FiducialtoModelDistance capitalization should be FiducialToModelDistance
- [x] Type: in many places in FiducialtoModelDistance.py Hausdorff is misspelled (as Hausdroff)
- [x] CMakeLists.txt and module folder must be in the root of the repository
- [x] Update extension icon
- [x] Repository name must start with Slicer: instead of `Fiducials-to-Model-Distance` it has to be something like `SlicerFiducialsToModelDistance`
- [x] Use parameter node to save selections done in the GUI into the scene (see https://discourse.slicer.org/t/how-to-save-slicer-scene-with-both-slicer-data-and-with-self-variables-within-custom-widget/9830/2?u=lassoan)

**Comment by ReynoldsJ20** [comment]
Hi Andras, did you see my question in the thread which you linked above? Thanks.

**Comment by lassoan** [comment]
I've answered now.

**Comment by ReynoldsJ20** [comment]
Hi, I think I finally have got the parameter node to do what I want it to do i.e. when I save and open the scene the FidcualsToModelDistance has all the same settings and inputs as when I saved the scene. I can also make multiple parameter nodes and change their settings and the settings are saved in the parameter node are restored when I select that parameter node again. I found this very complicated and I still don't fully understand how or why it works so there may be some strange/redundant code in there. I borrowed a lot of the parameter node code from VectorToScalarVolume as this had a non-singleton parameter node setup. The updated code is in the parameter node branch

**Comment by lassoan** [comment]
Thank you. I've sent a pull request (https://github.com/ReynoldsJ20/SlicerFiducialsToModelDistance/pull/4) with an overall cleanup and simplification of the module.

**Comment by ReynoldsJ20** [comment]
Thanks so much, that looks a lot more clean. Hopefully it didn't take you too long and my coding attempts weren't too much of a hindrance.

I was happy to see these lines from ``updateGUIFromParameterNode`
```
wasBlocked = self.ui.inputPointsSelector.blockSignals(True)
self.ui.inputPointsSelector.setCurrentNode(self._parameterNode.GetNodeReference("InputPoints"))
self.ui.inputPointsSelector.blockSignals(wasBlocked)
```
I spent a long time yesterday trying to figure out how to stop the parameters updating again when the ``updateGUIFromParameterNode` changed the nodes in the input selector boxes. I ended up making separate methods for each node which worked but it didn't seem right.

What would be the difference between the code above and this:
```
self.ui.inputPointsSelector.blockSignals(True)
self.ui.inputPointsSelector.setCurrentNode(self._parameterNode.GetNodeReference("InputPoints"))
self.ui.inputPointsSelector.blockSignals(False)

```
I was just wondering why you structured it with the wasBlocked variable?

Thanks again.

**Comment by lassoan** [comment]
After we temporarily block signals we must restore the previous blocked/unblocked state. We cannot just simply unblock it.

**Comment by ReynoldsJ20** [comment]
Great thanks, I had a play in the python inter-actor and I see how it restores the original state with the true/false outputs.

What do I need to do now to submit the extension?

**Comment by lassoan** [comment]
You just need to update these lines: https://github.com/ReynoldsJ20/SlicerFiducialsToModelDistance/blob/master/CMakeLists.txt#L7-L13

Also update description of the extension (see link above) and module (https://github.com/ReynoldsJ20/SlicerFiducialsToModelDistance/blob/master/FiducialToModelDistance/FiducialToModelDistance.py#L22) to reflect that it can compute error for two sets of fiducials, too (not just between mode and fiducials).

**Comment by ReynoldsJ20** [comment]
Ok, I think I have done both those things correctly.

**Comment by lassoan** [comment]
Icon urls must be the download urls, for example https://raw.githubusercontent.com/ReynoldsJ20/SlicerFiducialsToModelDistance/master/FiducialtoModelDistance.png

Nitpick in extension description: results are displayed in two tables (not just "a table")

**Comment by ReynoldsJ20** [comment]
Both descriptions updated and icon URL is updated.

**Comment by lassoan** [comment]
Almost perfect. screenshoturls must be list of URLs to images separated by spaces. Example: set(EXTENSION_SCREENSHOTURLS "http://www.slicer.org/slicerWiki/images/8/87/SlicerRT_0.10_IsocenterShiftingEvaluation.png http://www.slicer.org/slicerWiki/images/e/ef/SlicerRT_0.11_ProstateLoaded_Beams_ThresholdedDose.png http://www.slicer.org/slicerWiki/images/4/40/SlicerRtFundingSources.png")

**Comment by ReynoldsJ20** [comment]
Ok, I have put the two download links with spaces in between

**Comment by lassoan** [comment]
Thank you, I've submitted the extension to the extension index. If everything goes well then it will show up in Slicer's Extension Manager tomorrow.

**Comment by ReynoldsJ20** [comment]
Great thanks for the help!

**Comment by ReynoldsJ20** [comment]
Great, thanks for the help!

**Comment by lassoan** [comment]
The module shows up and can be installed form the extension manager but it does not appear in the module list. The problem was that the module name was spelled inconsistently (to/To and Fiducial/Fiducials). I've sent a pull request (https://github.com/ReynoldsJ20/SlicerFiducialsToModelDistance/pull/5) that should fix it.

Please also add the "3d-slicer-extension" topic to the repository:
- [ ] Repository is associated with 3d-slicer-extension GitHub topic so that it is listed here. To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics

**Comment by ReynoldsJ20** [comment]
Thanks for the pull request. I have added the 3d slicer topic as mentioned above. Thanks again, I think I am slowly learning slicer programming with your help.

**Comment by ReynoldsJ20** [comment]
Thanks, pull request is merged now
